version: "3.8"
services:
  server:
    build: .
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - mysqldb
    volumes:
      - app-data:/var/lib/app
  mysqldb:
    image: mysql:latest
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: demo
      MYSQL_USER: gorka
      MYSQL_PASSWORD: root123
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
  app-data: